id: P5A43CC5C
initial_creation_type: input
source_metadata:
  title: Kadam Series
  language: en
  description: Art
  volume:
    b220ec3359f64bb795bd7aa28eff390e:
      title: Description of a Kadam Thangka
      parent: Art
created_at: '2022-03-01T04:01:24.557013'
last_modified_at: '2022-03-01T04:01:24.557019'
